# Generated by Django 4.0.4 on 2022-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_product_banneradd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='modeOfPayment',
            new_name='provider_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
