# Generated by Django 4.0.4 on 2022-05-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_modeofpayment_order_provider_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
