# Generated by Django 4.0.4 on 2022-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
