# Generated by Django 4.0.4 on 2022-05-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
