# Generated by Django 4.0.4 on 2022-05-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='phonenumbers',
            new_name='phonenumber',
        ),
    ]
