# Generated by Django 4.0.4 on 2022-05-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_phonenumber_retailer_phonenumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='phonenumbers',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='api.retailer'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='phonenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
