# Generated by Django 4.0.4 on 2022-05-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_retailer_phonenumbers_product_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='phonenumber',
            new_name='phonenumbers',
        ),
    ]
