# Generated by Django 4.0.4 on 2022-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounts',
            field=models.FloatField(default=0),
        ),
    ]
